Exo 1

USE `webdevelopment`;
CREATE TABLE `language` (id INT PRIMARY KEY NOT NULL AUTO_INCREMENT, language VARCHAR(255));

Exo 2

CREATE TABLE `tools` (id INT PRIMARY KEY AUTO_INCREMENT, tool VARCHAR(255));

Exo 3

CREATE TABLE `frameworks` (id INT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(255));

Exo 4 

CREATE TABLE `libraries` (id INT PRIMARY KEY AUTO_INCREMENT, library VARCHAR(255));

Exo 5

CREATE TABLE `IDE` (id INT PRIMARY KEY AUTO_INCREMENT, ideName VARCHAR(255));

Exo 6

CREATE TABLE IF NOT EXISTS `frameworks` (id INT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(255));

Exo 7 

DROP TABLE IF EXISTS `tools`;

Exo 8 

DROP TABLE `libraries`; 

Exo 9 

DROP TABLE `IDE`;

TP

CREATE DATABASE `codex`;
USE `codex`;
CREATE TABLE `clients` (id INT PRIMARY KEY AUTO_INCREMENT , lastname VARCHAR(255), firstname VARCHAR(255), birthDate DATE, address VARCHAR(255), firstPhoneNumber INT, secondPhoneNumber INT, mail VARCHAR(255));